<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="8" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="491" started-at="2014-08-20T14:36:17Z" finished-at="2014-08-20T14:36:18Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="491" started-at="2014-08-20T14:36:17Z" finished-at="2014-08-20T14:36:18Z">
      <class name="com.atmecs.com.atmecs.ReportCreator.TestClass">
        <test-method status="PASS" signature="test1()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test1" duration-ms="46" started-at="2014-08-20T20:06:17Z" finished-at="2014-08-20T20:06:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test2" duration-ms="1" started-at="2014-08-20T20:06:17Z" finished-at="2014-08-20T20:06:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test3()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test3" duration-ms="1" started-at="2014-08-20T20:06:17Z" finished-at="2014-08-20T20:06:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="test4()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test4" duration-ms="0" started-at="2014-08-20T20:06:17Z" finished-at="2014-08-20T20:06:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="test5()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test5" duration-ms="0" started-at="2014-08-20T20:06:17Z" finished-at="2014-08-20T20:06:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="test6()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test6" duration-ms="1" started-at="2014-08-20T20:06:18Z" finished-at="2014-08-20T20:06:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method status="FAIL" signature="test7()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test7" duration-ms="9" started-at="2014-08-20T20:06:18Z" finished-at="2014-08-20T20:06:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.atmecs.com.atmecs.ReportCreator.TestClass.test7(TestClass.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
        <test-method status="PASS" signature="test8()[pri:0, instance:com.atmecs.com.atmecs.ReportCreator.TestClass@6a0f411]" name="test8" duration-ms="1" started-at="2014-08-20T20:06:18Z" finished-at="2014-08-20T20:06:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test8 -->
      </class> <!-- com.atmecs.com.atmecs.ReportCreator.TestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
